# Request to let user sign up

# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname":"John",
#     "email":"john@gmail.com",
#     "password":"Saban1973"
# }

# Request to let user sign in

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email":"john@gmail.com",
#     "password":"Saban1973"
# }


# TestToken for a user
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODVhNmZmNDQxNjRhN2JlNzkyMjkzYiIsImlhdCI6MTcwMzI1Nzg1Nn0.gv3XOe7zyXqg9dPOusXzU3h9lmw8eeWbMFCUmOEUgiM


# Route to let user post a blog
# POST http://localhost:3000/create-blog
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODVhNmZmNDQxNjRhN2JlNzkyMjkzYiIsImlhdCI6MTcwMzMxODQ5N30.gkEEZjAa5t01ePE-UpEuax9oLzD105hmwPD1IS-gARw

# {
#     "title":"test- title",
#     "banner":"testBanner.com",
#     "description":"test description",
#     "content":{
#         "blocks":[1,2]
#     },
#     "tags":["tag1","tag2"]
# }

# POST  http://localhost:3000/latest-blogs
# Content-Type: application/json

# {
#     "page":"1"
# }

# GET http://localhost:3000/trending-blogs

# POST http://localhost:3000/all-latest-blogs-count
# Content-Type: application/json

# {
    
# }

# POST http://localhost:3000/search-blogs
# Content-Type: application/json

# {
#     "page":"1",
#     "tag":"bb"
# }


# POST http://localhost:3000/search-blogs-count
# Content-Type: application/json

# {
#     "tag":"jee"
# }

POST http://localhost:3000/get-profile
Content-Type: application/json

{
    "username":"saquib"
}